
FROM wyveo/nginx-php-fpm:latest as BACKEND
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests -q -y php8.0-sqlite3

WORKDIR /usr/share/nginx/
